---
#                     _                 _ _  __          __     ___            _        
#  ___  ___ _ __   __| |_ __ ___   __ _(_) |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# / __|/ _ \ '_ \ / _` | '_ ` _ \ / _` | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# \__ \  __/ | | | (_| | | | | | | (_| | | | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |___/\___|_| |_|\__,_|_| |_| |_|\__,_|_|_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                           \_\          /_/                            
# create-user
- name: create-user | Each group should be created
  group:
    state: "present"
    name:  "{{ item.group }}"
    gid:   "{{ item.gid }}"
  with_items:
    - "{{ sendmail.user.mta }}"
    - "{{ sendmail.user.msa }}"
    - "{{ sendmail.user.mda }}"

- name: create-user | Each user should be created
  user:
    state: "present"
    name:  "{{ item.username }}"
    uid:   "{{ item.uid }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell }}"
    home:  "{{ item.home }}"
    comment: "{{ item.comment }}"
    createhome: "yes"
  with_items:
    - "{{ sendmail.user.mta }}"
    - "{{ sendmail.user.msa }}"
    - "{{ sendmail.user.mda }}"

- name: create-user | User {{ sendmail.user.msa.username }} should be belong to group {{ sendmail.user.mta.group }}
  user:
    name:   "{{ sendmail.user.msa.username }}"
    groups: "{{ sendmail.user.mta.group }}"
    state:  "present"

