---
#                     _                 _ _  __          __     ___            _        
#  ___  ___ _ __   __| |_ __ ___   __ _(_) |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# / __|/ _ \ '_ \ / _` | '_ ` _ \ / _` | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# \__ \  __/ | | | (_| | | | | | | (_| | | | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |___/\___|_| |_|\__,_|_| |_| |_|\__,_|_|_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                           \_\          /_/                            
# tasks file for ar-sendmail-src
- { include: install-pkg.yml, when: sendmail.updateonly == false }
- { include: to-sendmail.yml, when: ansible_os_family == "RedHat" }
- { include: create-user.yml, when: sendmail.updateonly == false }
- { include: get-archive.yml }
- { include: compile-src.yml }
- { include: make-config.yml, when: sendmail.updateonly == false }
- { include: set-mailbox.yml }
- { include: boot-script.yml }
- { include: port-config.yml }

