---
#                     _                 _ _  __          __     ___            _        
#  ___  ___ _ __   __| |_ __ ___   __ _(_) |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# / __|/ _ \ '_ \ / _` | '_ ` _ \ / _` | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# \__ \  __/ | | | (_| | | | | | | (_| | | | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |___/\___|_| |_|\__,_|_| |_| |_|\__,_|_|_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                           \_\          /_/                            
# port-config
- name: port-config | SMTP(25) port should be opened
  firewalld:
    service:   "smtp"
    state:     "enabled"
    immediate: true
    permanent: true

- name: port-config | Submission(587) port should be opened
  firewalld:
    port:      "587/tcp"
    state:     "enabled"
    immediate: true
    permanent: true

