---
#                     _                 _ _  __          __     ___            _        
#  ___  ___ _ __   __| |_ __ ___   __ _(_) |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# / __|/ _ \ '_ \ / _` | '_ ` _ \ / _` | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# \__ \  __/ | | | (_| | | | | | | (_| | | | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |___/\___|_| |_|\__,_|_| |_| |_|\__,_|_|_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                           \_\          /_/                            
# set-mailbox
- name: set-mailbox | mailboxes of each user should be created
  when: email.creatembox == true
  register: sendmail_create_mailbox
  changed_when: sendmail_create_mailbox.rc < 0
  shell: >
    {{ virtmail.install }}/sbin/make-vmailbox {{ item.address }}
  with_items: "{{ email.accounts }}"

- name: set-mailbox | SMTP-AUTH accounts should be created
  when: email.creatembox == true
  register: make_smtp_auth_passwd
  changed_when: make_smtp_auth_passwd.rc == 0
  failed_when: make_smtp_auth_passwd.rc == 1
  shell: >
    {{ virtmail.install }}/sbin/make-sasl-passwd {{ item.address }} {{ item.password }}
  args:
    chdir: "/etc"
  with_items: "{{ email.accounts }}"

- name: set-mailbox | /etc/sasldb2 should be created
  when: email.creatembox == true
  file:
    path:  "/etc/sasldb2"
    mode:  "0640"
    owner: "root"
    group: "root"
    state: "file"

